# Generated by Django 2.1 on 2019-11-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191115_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_order',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
