# Generated by Django 2.1 on 2019-11-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20191118_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('deliver_order', 'Доставка заказа'), ('cancel_order', 'Отмена заказа')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
